### ISSUE TITLE
qconf cannot build qt6 project 

### ISSUE THREAD

**Issue by Brensom** [psi-im/qconf#17]
qconf has dependencies qt5-base and qt5-translations, but If I need to compile a project with qt6 support, then I get an error:
`Project ERROR: Qt 5.15.10 is not suited to compile PreviSat. Use Qt 6.4.3 in preference`

And there is no option to specify to use qt6.

**Comment by Ri0n** [comment]
it's nice to see somebody is still interested in this project while cmake has already conquered the world :)
I'll take a look when I have some spare time.

**Comment by Vitozz** [comment]
Psi doesn't support qt6. Am I wrong?

**Comment by Ri0n** [comment]
@Vitozz I believe it's not about Psi. qconf is a general purpose tool for Qt apps.

**Comment by Neustradamus** [comment]
@jkarneges: Good job for QConf and JDNS :)
- https://github.com/psi-im/qconf/commit/71c452f743d5a85fabb7b93a698d43871b14c431
- https://github.com/psi-im/qconf/commit/f8177fdfe4b2bafc9a5f910c5c194ccdebb6cb5d
- https://github.com/psi-im/qconf/commit/c5c19f0355250a7ae4a7ab2ed5ea5624a2d8a418
- https://github.com/psi-im/jdns/commit/f146ede307943ef0d73cbb159bded5d33bdc8930
